# Generated by Django 4.1.3 on 2022-12-02 07:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blog',
            old_name='thumnail',
            new_name='thumbnail',
        ),
    ]
