# Generated by Django 4.1.3 on 2022-12-02 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0004_remove_comment_active_alter_comment_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='context',
            field=models.TextField(blank=True, null=True),
        ),
    ]
