# Generated by Django 4.1.3 on 2022-12-03 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0006_newsletter_rename_context_comment_body_comment_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='name',
            field=models.CharField(max_length=150),
        ),
    ]
